version: "3"
services:
  dockerintegraation:
#    image: organization-service
    build: ./spring-boot-crud-example-master    
    container_name: "dockermysqlintegration"    
    ports:
      - "8083:8083"
    networks:
      - organization-mysql
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:latest    
    container_name: "mysql"  
    ports :
      - "3306:3306"
    networks:
      - organization-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=organizationdb

networks:
  organization-mysql:
