version: "3"
services:

  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    # voulme : /var/mysql/backupdata
    ports:
      - "3306:3306"
    expose:
      - 3306
    networks:
      - organization-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dockerdb
    


  dockerintegraation:
#    image: organization-service
    build: ./spring-boot-crud-example-master
    image: dockermysqlintegration:1.0
    container_name: "dockermysqlintegration"
    restart: always
    ports:
      - "8083:8083"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dockerdb
      - MYSQL_PORT=3036
      - MYSQL_HOST=mysqldb
      - MYSQL_USER=root
    networks:
      - organization-mysql
    depends_on:
      mysqldb:
    


networks:
  organization-mysql:
