version: "3"
services:
  organization:
#    image: organization-service
    build: ./spring-boot-crud-example-master
    ports:
      - "8083:8083"
    networks:
      - organization-mysql
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:latest
    voulmes :
        - mysql-voulme:/var/lib/mysql
    ports :
      - "127.0.0.1:3306:3306"
    networks:
      - organization-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=organizationdb

networks:
  organization-mysql:
