spring:
  datasource:
    username: root
    password: Welcome@#$99
    url: jdbc:mysql://172.26.0.1:3306/organizationdb?useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8083
    
