spring:
  datasource:
    username: root
    password: ${MYSQL_ROOT_PASSWORD}
    url: jdbc:mysql://mysqldb:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8083
    
